name:                readert-writert
version:             0.1.0.0
github:              "ssanj/readert-writert"
license:             BSD3
author:              "sanjiv sahayam"
maintainer:          "sanjsmailbox@gmail.com"
copyright:           "(c) 2017 sanjiv sahayam"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/ssanj/readert-writert#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  readert-writert-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - readert-writert
    - transformers
    - containers

tests:
  readert-writert-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - readert-writert
